name: learn-github-actions

run-name: ${{ github.actor }} is learning GitHub Actions

on: 
  push:
    branches:
      - main

jobs:
  check-bats-version:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install -g bats
      - run: bats -v

  create:
    runs-on: ubuntu-22.04
    needs: check-bats-version
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: sudo apt update && sudo apt install curl

      
