name: node-action

on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Restore cached Primes
      id: cache-primes-restore
      uses: actions/cache/restore@v3
      with:
        path: |
          react-app/package.json
          react-app/node_modules
        key: ${{ runner.os }}-primes
    
    - name: Set Node environment
      uses: actions/setup-node@v3
      with: 
        node-version: 18.1.0
        cache: 'yarn'
        cache-dependency-path: |
          react-app/package.json
          react-app/node_modules

    - name : Build      
      run: |
        cd react-app
        yarn test
        yarn install
        yarn build
    
    - name: Save Primes
      id: cache-primes-save
      uses: actions/cache/save@v3
      with:
        path: |
          react-app/package.json
          react-app/node_modules
        key: ${{ steps.cache-primes-restore.outputs.cache-primary-key }}
