name: node-action

on:
  push:
    branches:
      - main
  workflow_dispatch:      

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set Node environment
      uses: actions/setup-node@v3
      with: 
        node-version: 18.1.0
        cache: 'yarn'
        cache-dependency-path: |
          react-app/package.json
          react-app/node_modules

    - run: |
        cd react-app
        yarn install
        yarn build       
