name: node-action

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - dev 
        
jobs:
  deploy-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set Node environment
      uses: actions/setup-node@v3
      with: 
        node-version: 18.1.0
        cache: 'yarn'
        cache-dependency-path: |
          react-app/package.json
          react-app/node_modules

    - name: Build      
      run: |
        cd react-app
        yarn install
        yarn build

  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    
    - name: Set Node environment
      uses: actions/setup-node@v3
      with: 
        node-version: 18.1.0
        cache: 'yarn'
        cache-dependency-path: |
          react-app/package.json
          react-app/node_modules

    - name: Build      
      run: |
        cd react-app
        yarn install
        yarn build

    - name: Docker
      run: |
        docker --version
    
          
        
